# Generated by Django 4.2.5 on 2023-09-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='photo_path',
            field=models.ImageField(default='media/photo/2023/09/08/pgadmin.png', upload_to='photo/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
