# Generated by Django 4.2.5 on 2023-09-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_photo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Категория')),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo_path',
            field=models.ImageField(default='/photo/2023/09/08/pgadmin.png', upload_to='photo/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Категория'),
        ),
    ]
