# Generated by Django 4.2.5 on 2023-09-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default='', verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo_path',
            field=models.ImageField(default='/photo/2023/09/08/pgadmin.png', upload_to='photo/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
