# Generated by Django 4.2.5 on 2023-09-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_alter_shop_photo_path_shop_category'),
        ('shop', '0004_shop_description_alter_shop_photo_path'),
    ]

    operations = [
    ]
