# Generated by Django 4.2.5 on 2023-09-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_merge_20230920_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='shop',
            name='arrival_date',
            field=models.DateField(auto_now=True, verbose_name='Дата прибытия товара'),
        ),
    ]
