# Generated by Django 4.2.5 on 2023-09-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_options_alter_shop_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления карточки товара'),
        ),
    ]
